server:
  tomcat:
    uri-encoding: UTF-8
  port: 8888
  context-path: /
  error:
    whitelabel:
      enabled: false
spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${pet.datasource.driver-class-name}
      url: jdbc:mysql://${pet.datasource.host}:${pet.datasource.port}/${pet.datasource.database}
      username: ${pet.datasource.username}
      password: ${pet.datasource.password}
  data:
    redis:
      host: ${pet.redis.host}
      port: ${pet.redis.port}
      password: ${pet.redis.password}
      database: ${pet.redis.database}
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: always
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  # 指定静态资源的路径
  mvc:
    # URL响应地址（Springboot默认为/**)
    static-path-pattern: /pic/**
  web:
    resources:
      static-locations: classpath:/static/,file:${upload.path}

mybatis:
  # mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.pet.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      pet:
        mapper: debug
        service: info
        controller: info
#服务器地址
serverUrl: http://localhost:8888
isDemo: false

pet:
  jwt:
    # 加密秘钥
    secret: firegoldfish
    # token有效时长 单位秒 7天604800
    adminExpire: 86400
    custExpire: 604800
    workExpire: 604800
    userTokenName: authentication
  alioss:
    endpoint: ${pet.alioss.endpoint}
    access-key-id: ${pet.alioss.access-key-id}
    access-key-secret: ${pet.alioss.access-key-secret}
    bucket-name: ${pet.alioss.bucket-name}
  wechat:
    appid: ${pet.wechat.appid}
    secret: ${pet.wechat.secret}
    mchid: ${pet.wechat.mchid}
    mch-serial-no: ${pet.wechat.mch-serial-no}
    private-key-file-path: ${pet.wechat.private-key-file-path}
    api-v3-key: ${pet.wechat.api-v3-key}
    we-chat-pay-cert-file-path: ${pet.wechat.we-chat-pay-cert-file-path}
    notify-url: ${pet.wechat.notify-url}
    refund-notify-url: ${pet.wechat.refund-notify-url}

# 文件上传
upload:
  path: c:\file
  # 文件服务器的图片子目录 （斜杠结尾）
  server: ${serverUrl}/pic

